/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiLightningBolt: typeof import('~icons/mdi/lightning-bolt')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StarterMessage: typeof import('./src/components/StarterMessage.vue')['default']
    StarterMessageLink: typeof import('./src/components/StarterMessageLink.vue')['default']
  }
}
